data = [
    {
        "name": "Instagram",
        "follower_count": 565,
        "description": "Social media platform",
        "country": "United States",
    },
    {
        "name": "Cristiano Ronaldo",
        "follower_count": 495,
        "description": "Footballer",
        "country": "Portugal",
    },
    {
        "name": "Ariana Grande",
        "follower_count": 339,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "name": "Dwayne Johnson",
        "follower_count": 346,
        "description": "Actor and professional wrestler",
        "country": "United States",
    },
    {
        "name": "Selena Gomez",
        "follower_count": 355,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "name": "Kylie Jenner",
        "follower_count": 372,
        "description": "Reality TV personality and businesswoman and Self-Made Billionaire",
        "country": "United States",
    },
    {
        "name": "Kim Kardashian",
        "follower_count": 333,
        "description": "Reality TV personality and businesswoman",
        "country": "United States",
    },
    {
        "name": "Lionel Messi",
        "follower_count": 372,
        "description": "Footballer",
        "country": "Argentina",
    },
    {
        "name": "Beyoncé",
        "follower_count": 281,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "Neymar",
        "follower_count": 181,
        "description": "Footballer",
        "country": "Brasil",
    },
    {
        "name": "National Geographic",
        "follower_count": 244,
        "description": "Magazine",
        "country": "United States",
    },
    {
        "name": "Justin Bieber",
        "follower_count": 264,
        "description": "Musician",
        "country": "Canada",
    },
    {
        "name": "Taylor Swift",
        "follower_count": 231,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "Kendall Jenner",
        "follower_count": 263,
        "description": "Reality TV personality and Model",
        "country": "United States",
    },
    {
        "name": "Jennifer Lopez",
        "follower_count": 226,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "name": "Nicki Minaj",
        "follower_count": 204,
        "description": "Musician",
        "country": "Trinidad and Tobago",
    },
    {
        "name": "Nike",
        "follower_count": 247,
        "description": "Sportswear multinational",
        "country": "United States",
    },
    {
        "name": "Khloé Kardashian",
        "follower_count": 279,
        "description": "Reality TV personality and businesswoman",
        "country": "United States",
    },
    {
        "name": "Miley Cyrus",
        "follower_count": 187,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "name": "Katy Perry",
        "follower_count": 178,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "Kourtney Kardashian",
        "follower_count": 203,
        "description": "Reality TV personality",
        "country": "United States",
    },
    {
        "name": "Kevin Hart",
        "follower_count": 157,
        "description": "Comedian and actor",
        "country": "United States",
    },
    {
        "name": "Ellen DeGeneres",
        "follower_count": 127,
        "description": "Comedian",
        "country": "United States",
    },
    {
        "name": "Real Madrid CF",
        "follower_count": 127,
        "description": "Football club",
        "country": "Spain",
    },
    {
        "name": "FC Barcelona",
        "follower_count": 113,
        "description": "Football club",
        "country": "Spain",
    },
    {
        "name": "Rihanna",
        "follower_count": 81,
        "description": "Musician and businesswoman",
        "country": "Barbados",
    },
    {
        "name": "Demi Lovato",
        "follower_count": 142,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "name": "Victoria's Secret",
        "follower_count": 73.5,
        "description": "Lingerie brand",
        "country": "United States",
    },
    {
        "name": "Zendaya",
        "follower_count": 157,
        "description": "Actress and musician",
        "country": "United States",
    },
    {
        "name": "Shakira",
        "follower_count": 77.1,
        "description": "Musician",
        "country": "Colombia",
    },
    {
        "name": "Drake",
        "follower_count": 124,
        "description": "Musician",
        "country": "Canada",
    },
    {
        "name": "Chris Brown",
        "follower_count": 124,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "LeBron James",
        "follower_count": 136,
        "description": "Basketball player",
        "country": "United States",
    },
    {
        "name": "Vin Diesel",
        "follower_count": 83.9,
        "description": "Actor",
        "country": "United States",
    },
    {
        "name": "Cardi B",
        "follower_count": 143,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "David Beckham",
        "follower_count": 75.7,
        "description": "Footballer",
        "country": "United Kingdom",
    },
    {
        "name": "Billie Eilish",
        "follower_count": 106,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "Justin Timberlake",
        "follower_count": 66.9,
        "description": "Musician and actor",
        "country": "United States",
    },
    {
        "name": "UEFA Champions League",
        "follower_count": 99.8,
        "description": "Club football competition",
        "country": "Europe",
    },
    {
        "name": "NASA",
        "follower_count": 84.4,
        "description": "Space agency",
        "country": "United States",
    },
    {
        "name": "Emma Watson",
        "follower_count": 68.4,
        "description": "Actress",
        "country": "United Kingdom",
    },
    {
        "name": "Shawn Mendes",
        "follower_count": 70.7,
        "description": "Musician",
        "country": "Canada",
    },
    {
        "name": "Virat Kohli",
        "follower_count": 222,
        "description": "Cricketer",
        "country": "India",
    },
    {
        "name": "Gigi Hadid",
        "follower_count": 76.2,
        "description": "Model",
        "country": "United States",
    },
    {
        "name": "Priyanka Chopra Jonas",
        "follower_count": 83.3,
        "description": "Actress and musician",
        "country": "India",
    },
    {
        "name": "9GAG",
        "follower_count": 58,
        "description": "Social media platform",
        "country": "China",
    },
    {
        "name": "Ronaldinho",
        "follower_count": 68.3,
        "description": "Footballer",
        "country": "Brasil",
    },
    {
        "name": "Maluma",
        "follower_count": 62.8,
        "description": "Musician",
        "country": "Colombia",
    },
    {
        "name": "Camila Cabello",
        "follower_count": 65.5,
        "description": "Musician",
        "country": "Cuba",
    },
    {
        "name": "NBA",
        "follower_count": 72.4,
        "description": "Club Basketball Competition",
        "country": "United States",
    },
]
